### ISSUE TITLE
Prod deploys are failing: "module 'users.models' has no attribute 'validate_ip'"

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#190]
```
Jan 15 15:12:23 silentselene uwsgi[3187939]: Internal Server Error: /deploy
Jan 15 15:12:23 silentselene uwsgi[3187939]: Traceback (most recent call last):
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 55, in inner
Jan 15 15:12:23 silentselene uwsgi[3187939]:     response = get_response(request)
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 197, in _get_response
Jan 15 15:12:23 silentselene uwsgi[3187939]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "/usr/local/lib/python3.9/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Jan 15 15:12:23 silentselene uwsgi[3187939]:     return view_func(*args, **kwargs)
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "./thscoreboard/autodeploy.py", line 76, in deploy
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "./thscoreboard/autodeploy.py", line 33, in do_deploy
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 198, in call_command
Jan 15 15:12:23 silentselene uwsgi[3187939]:     return command.execute(*args, **defaults)
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 448, in execute
Jan 15 15:12:23 silentselene uwsgi[3187939]:     output = self.handle(*args, **options)
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 96, in wrapped
Jan 15 15:12:23 silentselene uwsgi[3187939]:     res = handle_func(*args, **kwargs)
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "/usr/local/lib/python3.9/dist-packages/django/core/management/commands/migrate.py", line 114, in handle
Jan 15 15:12:23 silentselene uwsgi[3187939]:     executor = MigrationExecutor(connection, self.migration_progress_callback)
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/executor.py", line 18, in __init__
Jan 15 15:12:23 silentselene uwsgi[3187939]:     self.loader = MigrationLoader(self.connection)
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/loader.py", line 58, in __init__
Jan 15 15:12:23 silentselene uwsgi[3187939]:     self.build_graph()
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/loader.py", line 229, in build_graph
Jan 15 15:12:23 silentselene uwsgi[3187939]:     self.load_disk()
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/loader.py", line 120, in load_disk
Jan 15 15:12:23 silentselene uwsgi[3187939]:     migration_module = import_module(migration_path)
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Jan 15 15:12:23 silentselene uwsgi[3187939]:     return _bootstrap._gcd_import(name[level:], package, level)
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "./users/migrations/0007_ipban.py", line 9, in <module>
Jan 15 15:12:23 silentselene uwsgi[3187939]:     class Migration(migrations.Migration):
Jan 15 15:12:23 silentselene uwsgi[3187939]:   File "./users/migrations/0007_ipban.py", line 20, in Migration
Jan 15 15:12:23 silentselene uwsgi[3187939]:     ('ip', models.TextField(validators=[users.models.validate_ip])),
Jan 15 15:12:23 silentselene uwsgi[3187939]: AttributeError: module 'users.models' has no attribute 'validate_ip'
```

**Comment by n-rook** [comment]
users.models definitely does have an attribute validate_ip, which makes this issue rather confusing

**Comment by 32th-System** [comment]
It's because the change isn't visible to uwsgi because it hadn't reloaded. We talked about this at one point . Just run `systemctl restart silentselene`

**Comment by 32th-System** [comment]
https://discord.com/channels/928695122558857216/928709192708157480/1057434059904655403
