### ISSUE TITLE
URLs of the form "/replays/th11/d3/ReimuA" returns an error

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#485]
iirc this is a defunct URL that used to work. I assume this is a user with a really old tab. The stack trace is:

```
Oct 15 11:25:57 silentselene uwsgi_python311[79286]: Internal Server Error: /replays/th11/d3/ReimuA
Oct 15 11:25:57 silentselene uwsgi_python311[79286]: Traceback (most recent call last):
Oct 15 11:25:57 silentselene uwsgi_python311[79286]:   File "/home/silentselene/silentselene-staging/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
Oct 15 11:25:57 silentselene uwsgi_python311[79286]:     response = get_response(request)
Oct 15 11:25:57 silentselene uwsgi_python311[79286]:                ^^^^^^^^^^^^^^^^^^^^^
Oct 15 11:25:57 silentselene uwsgi_python311[79286]:   File "/home/silentselene/silentselene-staging/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
Oct 15 11:25:57 silentselene uwsgi_python311[79286]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Oct 15 11:25:57 silentselene uwsgi_python311[79286]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 15 11:25:57 silentselene uwsgi_python311[79286]:   File "/home/silentselene/silentselene-staging/.venv/lib/python3.11/site-packages/django/views/decorators/http.py", line 43, in inner
Oct 15 11:25:57 silentselene uwsgi_python311[79286]:     return func(request, *args, **kwargs)
Oct 15 11:25:57 silentselene uwsgi_python311[79286]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 15 11:25:57 silentselene uwsgi_python311[79286]: TypeError: game_scoreboard() got an unexpected keyword argument 'difficulty'
Oct 15 11:25:57 silentselene uwsgi_python311[79286]: [ip address snipped] (92ms) 500 GET /replays/th11/d3/ReimuA
```

**Comment by n-rook** [comment]
Actually, there are a bunch of these in the logs, so I suspect they're coming from somewhere current.

**Comment by n-rook** [comment]
Or maybe not. Unclear :)
