### ISSUE TITLE
TH13 returns 500 error

### ISSUE THREAD

**Issue by jgdhs27** [n-rook/thscoreboard#493]
See https://www.silentselene.net/replays/th13
It's down on staging too: https://staging.silentselene.net/replays/th13
But it works locally for me.

**Comment by 32th-System** [comment]
```
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]: Internal Server Error: /replays/th13
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]: Traceback (most recent call last):
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:   File "/home/silentselene/silentselene-staging/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:     response = get_response(request)
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:                ^^^^^^^^^^^^^^^^^^^^^
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:   File "/home/silentselene/silentselene-staging/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:   File "/home/silentselene/silentselene-staging/.venv/lib/python3.11/site-packages/django/views/decorators/http.py", line 43, in inner
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:     return func(request, *args, **kwargs)
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:   File "/home/silentselene/silentselene-staging/project/thscoreboard/replays/views/replay_list.py", line 51, in game_scoreboard
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:     filter_options = _get_filter_options(game)
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:   File "/home/silentselene/silentselene-staging/project/thscoreboard/replays/views/replay_list.py", line 75, in _get_filter_options
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:     return _get_filter_options_th13(game)
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:   File "/home/silentselene/silentselene-staging/project/thscoreboard/replays/views/replay_list.py", line 111, in _get_filter_options_th13
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]:     filter_options["Difficulty"].remove("Overdrive")
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]: ValueError: list.remove(x): x not in list
Dec 30 12:44:30 silentselene uwsgi_python311[1966294]: [194.118.183.57] (37ms) 500 GET /replays/th13
```

**Comment by jgdhs27** [comment]
thanks. i dont know the exact cause of the issue, its probably translation, but i can fix it

**Comment by jgdhs27** [comment]
oops, this should only be closed once we actually fix it

**Comment by jgdhs27** [comment]
fixed
https://www.silentselene.net/replays/th13
