### ISSUE TITLE
Unable to parse th10 replay

### ISSUE THREAD

**Issue by jgdhs27** [n-rook/thscoreboard#502]
An error is thrown when trying to parse the attached file.

[th10_09.zip](https://github.com/n-rook/thscoreboard/files/14230218/th10_09.zip)

**Comment by jgdhs27** [comment]
stack trace:
```
Internal Server Error: /replays/upload
Traceback (most recent call last):
  File "C:\Users\Markus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Markus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Markus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Markus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Markus\thscoreboard\project\thscoreboard\replays\views\create_replay.py", line 57, in upload_file
    _ = _HandleReplay(request, file_contents)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Markus\thscoreboard\project\thscoreboard\replays\views\create_replay.py", line 44, in _HandleReplay
    return replay_parsing.Parse(replay_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Markus\thscoreboard\project\thscoreboard\replays\replay_parsing.py", line 1108, in Parse
    return _Parse10(replay)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Markus\thscoreboard\project\thscoreboard\replays\replay_parsing.py", line 450, in _Parse10
    header = th_modern.ThModern.from_bytes(rep_raw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return cls(KaitaiStream(BytesIO(buf)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Markus\thscoreboard\project\thscoreboard\replays\kaitai_parsers\th_modern.py", line 15, in __init__
    self._read()
  File "C:\Users\Markus\thscoreboard\project\thscoreboard\replays\kaitai_parsers\th_modern.py", line 19, in _read
    self.userdata = ThModern.Userdata(self._io, self, self._root)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Markus\thscoreboard\project\thscoreboard\replays\kaitai_parsers\th_modern.py", line 44, in __init__
    self._read()
  File "C:\Users\Markus\thscoreboard\project\thscoreboard\replays\kaitai_parsers\th_modern.py", line 66, in _read
    self.stage = ThModern.Crlfstring(self._io, self, self._root)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Markus\thscoreboard\project\thscoreboard\replays\kaitai_parsers\th_modern.py", line 76, in __init__
    self._read()
  File "C:\Users\Markus\thscoreboard\project\thscoreboard\replays\kaitai_parsers\th_modern.py", line 79, in _read
    self.value = (self._io.read_bytes_term(13, False, True, True)).decode(u"SJIS")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Markus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\kaitaistruct.py", line 343, in read_bytes_term      
    raise Exception(
Exception: end of stream reached, but no terminator 13 found
```

We fail to parse the header from this replay

**Comment by jgdhs27** [comment]
It's a v0.01a replay - that might be the cause. Kirbycomment also attempted to upload PCB 0.01 and SA 0.01a replays.
* The SA replay uploaded correctly.
* The PCB replay gave the error message `This replay is corrupted or otherwise malformed`.
* The MoF replay gives a 500 server error.
